// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWw4J0XdgU0h1KdjpLQixktgy0FJVDBj8',
    appId: '1:10737593836:web:085c3b328717f1d230a4c9',
    messagingSenderId: '10737593836',
    projectId: 'urinebags',
    authDomain: 'urinebags.firebaseapp.com',
    storageBucket: 'urinebags.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV68owG7AKDwcLdjapqEgH-Q7CJzYoCEs',
    appId: '1:10737593836:android:4b3e9ac986ea368f30a4c9',
    messagingSenderId: '10737593836',
    projectId: 'urinebags',
    storageBucket: 'urinebags.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP36W8iS1JtMeiXugxK8aOn17JrF4EAls',
    appId: '1:10737593836:ios:4423fcd3aecedeed30a4c9',
    messagingSenderId: '10737593836',
    projectId: 'urinebags',
    storageBucket: 'urinebags.firebasestorage.app',
    iosBundleId: 'com.example.urineBag',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP36W8iS1JtMeiXugxK8aOn17JrF4EAls',
    appId: '1:10737593836:ios:4423fcd3aecedeed30a4c9',
    messagingSenderId: '10737593836',
    projectId: 'urinebags',
    storageBucket: 'urinebags.firebasestorage.app',
    iosBundleId: 'com.example.urineBag',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWw4J0XdgU0h1KdjpLQixktgy0FJVDBj8',
    appId: '1:10737593836:web:3b4eaed7afe254a330a4c9',
    messagingSenderId: '10737593836',
    projectId: 'urinebags',
    authDomain: 'urinebags.firebaseapp.com',
    storageBucket: 'urinebags.firebasestorage.app',
  );
}
